spring:
  application:
    name: Jet Drive

  datasource:
    # Postgres DB
    #url: jdbc:postgresql://localhost:5432/jet_drive
    #username: postgres
    #password:
    #driver-class-name: org.postgresql.Driver

    # H2 DB
    url: jdbc:h2:mem:test_db
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true
    #database-platform: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop

jwt:
  secret: ZkdJcFJ6N1JPdTVPZjB4c0RqNDNUQ0JuS1NLaHU0ZFM= #{JWT_SECRET_V2_BASE64}

google:
  clientId: 551260504895-mofqeookk23lmol3g8r9npjol9r03fm5.apps.googleusercontent.com #{GOOGLE_CLIENT_ID}

#logging:
#  level:
#   root: INFO

server:
  port: 8001