spring:
  application:
    name: Jet Drive

  datasource:
    url: jdbc:h2:mem:test_db # jdbc:postgresql://localhost:5432/tenant_service_db
    username: sa # postgres
    password:
    driver-class-name: org.h2.Driver # org.postgresql.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect # org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop

jwt:
  secret: ZkdJcFJ6N1JPdTVPZjB4c0RqNDNUQ0JuS1NLaHU0ZFM= #{JWT_SECRET_V2_BASE64}

#logging:
#  level:
#   root: INFO